### ISSUE TITLE
Automatic save after changes and persistent selection of entity

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-studio-config#12]
**Description**
These are minor changes that would greatly help improve the Taipy Studio Config experience.
- Each change in Taipy Studio (either in the entities or graph) should be directly reported to the toml file so that they are never different.
- Saving the configuration or changing a parameter will unselect the selected entity. Having it still selected even after saving or changing a property would be a great improvement.

![change_in_property](https://user-images.githubusercontent.com/98709993/214867533-568319f6-623c-4e0a-b108-2b2b7e9c173b.gif)

**Comment by FredLL-Avaiga** [comment]
Toml file and diagram / side bar should always be aligned.
Can you describe a case when they're not ?

**Comment by FlorianJacta** [comment]
There are not aligned when creating links. If the file hasn't been saved, links between unsaved entities will not be created. I can provide an example if needed.

**Comment by FredLL-Avaiga** [comment]
does it work when the file has been saved once ?

**Comment by FlorianJacta** [comment]
I have the problem even if I saved it once before

**Comment by FredLL-Avaiga** [comment]
Adding Element name change

**Comment by FredLL-Avaiga** [comment]
What kind of perspective ?
