### ISSUE TITLE
python.pythonPath is deprecated 

### ISSUE THREAD

**Issue by FredLL-Avaiga** [Avaiga/taipy-studio-config#26]
use command: python.interpreterPath (will allow to use the venv setting)
or default to configuration python.defaultInterpreterPath
or use "python"

**Comment by FredLL-Avaiga** [comment]
@dinhlongviolin1 I guess you should use the same way

**Comment by dinhlongviolin1** [comment]
I have tried it but this configuration is defined by the user, not the chosen interpreter by the user.

**Comment by FredLL-Avaiga** [comment]
checkout https://github.com/microsoft/vscode-python/wiki/Setting-descriptions#experience

You get the interpreter choosen by the command "Python: Select Interpreter"

Used like
```
commands.executeCommand("python.interpreterPath", workspace.workspaceFolders?.map(({uri}) => uri.fsPath)).then(
      (pythonPath: string) => doGetFilesFromPythonPackage(pythonPath, file, packages, resolve, reject),
      () => doGetFilesFromPythonPackage(workspace.getConfiguration("python").get("defaultInterpreterPath", "python"), file, packages, resolve, reject)
    );
```
