### ISSUE TITLE
BUG - Attributes with default values should be populated

### ISSUE THREAD

**Issue by jrobinAV** [Avaiga/taipy-studio-config#32]
When creating a new config section ( DataNodeConfig , TaskConfig, ... ), The attributes with a default value (in the schema) must be automatically populated with the default value in Studio Config Builder.

**Related question:** 
This means all attributes with a default value automatically appear on Studio when creating a section.
Do we want to add more attributes (like `function` for TaskConfig, that have no default value)?

**Comment by FredLL-Avaiga** [comment]
For now, Studio-config defines the list of properties added when a new element is created.
the default value is also proposed when adding a property to an element
