### ISSUE TITLE
BUG- Studio does not detect functions in module and write them incorrectly 

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-studio-config#35]
**Description**
The problem arises when a function is in a module. Taipy will not detect it and writing it manually will not attach automaticall the name of the module before it.

**How to reproduce**

![toml_function](https://user-images.githubusercontent.com/98709993/219685669-b7d1cc57-70e8-4e34-94ee-90603381e556.gif)

**Expected behavior**
We should be able to detect the function inside the folder or at least attach automatically the prefix to the function name (ex: *algos.algos*).

**Runtime environment**
 - Taipy Studio Config version: 1.0.1

**Comment by FredLL-Avaiga** [comment]
Is the issue the same if you set the python as main module first ? (right click python file)

**Comment by FlorianJacta** [comment]
If *algos/algos.py* is my main module, I can select *fct* through Taipy Studio but it will write '__main__.fct:function' which is correct but not what I want.
