### ISSUE TITLE
BUG- Sections not appearing in Taipy Studio view

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-studio-config#40]
**Description**
Data Nodes, Tasks, Pipelines, and Scenarios sections are not appearing in Taipy Studio Config sidebar.

**How to reproduce**
- Have the up-to-date VS Code installed (1.77.2)
- Install the latest Taipy Studio version

**Expected behavior**
Data Nodes, Tasks, Pipelines, and Scenarios sections should appear as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/98709993/231505577-150e6328-05d8-427f-99a1-1255acb9d4d9.png)

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 11
 - Visual Studio Code version: 1.77.2
 - Taipy Studio Config version: 1.0.2

**Comment by FredLL-Avaiga** [comment]
https://code.visualstudio.com/api/references/when-clause-contexts#comparison-operators

**Comment by FredLL-Avaiga** [comment]
1.0.3 published
https://marketplace.visualstudio.com/items?itemName=Taipy.studio-config
