### ISSUE TITLE
Visualize the contents of data nodes and the execution flow

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-studio-config#60]
**What would that feature address**
Two beta testers reported that they did not see the point of Taipy Core as they already knew how to code data pipelines in only Python and features like caching don't justify the steep learning curve of Core.

They did say though that visualization of the data pipeline can be interesting if it is well done.

***Description of the ideal solution***
Data Nodes in Studio should display information about the data contained on the view: type, shape, .head...
During execution, the queued tasks, the running tasks and tasks that fail should be highlighted
Something similar to Pyflow's execution flow:
![flow_example](https://github.com/Avaiga/taipy-core/assets/62465003/80344979-296b-4ee1-b587-49de09bdac01)

**Comment by jrobinAV** [comment]
"During execution, the queued tasks, the running tasks and tasks that fail should be highlighted
Something similar to Pyflow's execution flow:"
This is irrelevant for Studio-config. Studio-config does not relate to a runtime execution flow but only to a Configuration. 
So there is no data to display, nothing executed so no failure, no job status, no actual flow... 

However, this could be feasible in a runtime application with a Core visual element. We already have a scenario_dag. We might want to add more features on it at a point. Note that in a visual element, this will benefit the end user, while your issue suggest to provide value to the developer.

Another possibility would be to display more configuration attributes (properties, scope, default_data, python code for functions, python code for comparators, ...). These could be displayed but I am not sure about the added value for the developer at this point. If this is what you want, please open another ticket.

I would like to close this ticket.

Are you ok with that ? @AlexandreSajus @FabienLelaquais

**Comment by AlexandreSajus** [comment]
I understand. My take on this is that the current state of Taipy Core is fine. It addresses the issues of a market that does not include all Python developers (Students, Researchers, and people that want to prototype) but focuses on companies that want to deploy data pipelines in production. This is not a problem, but if we ever want to extend Core's reach, we should think of ways to make it more visual and catchy. I am okay with closing the issue.
