### ISSUE TITLE
BUG-Setting the function of a task node empties the details tab permanently

### ISSUE THREAD

**Issue by AlexandreSajus** [Avaiga/taipy-studio-config#83]
**Description**
Selecting a Task Node and setting its function property will permanently empty Taipy Studio's details tab. The Details tab will be empty even when selecting a new node (see attached video). The only way to unstuck the situation is by closing and reopening the Details tab.

**How to reproduce**
A sequence of events:
- Select a task node
- Assign a function to the task node in the details tab of Taipy Studio
- Select another node; the details tab will be empty

**Expected behavior**
The details tab should always display the properties of the selected node

**Screenshots**

https://github.com/Avaiga/taipy-studio-config/assets/62465003/cfdc9d09-30f8-4df9-a4a4-95fe920dd6d8

**Runtime environment**
Please specify relevant indications.
 - OS: Windows 11
 - Visual Studio Code version: 1.82.2
 - Taipy Studio Config version: 1.1.0

**Comment by FredLL-Avaiga** [comment]
can you try with 2.0 pre-release ?

**Comment by AlexandreSajus** [comment]
How do I install the 2.0. It seems unavailable on VSCode (I only have access to 1.0 and 1.1)
![image](https://github.com/Avaiga/taipy-studio-config/assets/62465003/dd290be0-d177-42f4-b7e2-2b1cd2487dbc)

**Comment by AlexandreSajus** [comment]
Fixed in 2.0
