### ISSUE TITLE
BUG-Data Node should disappear from additional_data_nodes

### ISSUE THREAD

**Issue by FlorianJacta** [Avaiga/taipy-studio-config#93]
**Description**
Data Nodes when attached to a task should disappear from the additional_data_nodes section.

**How to reproduce**
- Create a config and scenario, enter the scenario view
- Create a Data Node
- Add the Data Dode in the additional_data_nodes
- Attach it to a task

**Expected behavior**
It should disappear from the list of additional data nodes as it is now attached to a task.

**Screenshots**
![image](https://github.com/Avaiga/taipy-studio-config/assets/98709993/1a169f0d-bccc-401d-9f93-57ec018e780d)

**Runtime environment**
 - Taipy Studio Config version: 2.0.0

**Comment by FredLL-Avaiga** [comment]
I thought this was supported if not encouraged?

**Comment by FlorianJacta** [comment]
What do you mean? If a data node is linked to a task, it is not an *additional_data_nodes* or at least, this is what I think

**Comment by jrobinAV** [comment]
Absolutely. An additional data node is a data node part of the scenario that is not linked to any task of the scenario.
